### ISSUE TITLE
[BUG] Crashes app when app name contains spaces

### ISSUE THREAD

**Issue by chronikum** [hiddevdploeg/Billboard#20]
Hello, during development I found this issue

<img width="703" alt="image" src="https://github.com/hiddevdploeg/Billboard/assets/34622984/96105bba-d71e-4ac6-8ef0-3bbc4d5008ac">

It seems like, looking at the frame variables that appName seems to cause the the issue

<img width="289" alt="image" src="https://github.com/hiddevdploeg/Billboard/assets/34622984/f82b6012-0c5e-4868-a0b5-e4d9c372cc52">

because the url cannot be constructed, as there is a space in the app name.
Of course, this would be valid for any character that is not allowed in urls. 

Several apps have this issue when looking at the default list:

https://billboard-source.vercel.app/ads.json

**Comment by omit2c** [comment]
It's also not necessary for the AppStore link to have the app name in it. 
The link will also work like this: `https://apps.apple.com/app/id\(appID)`

**Comment by hiddevdploeg** [comment]
Should be fixed with #21
