### ISSUE TITLE
Again crashing at clicking on Banner sometimes (when link not available) 

### ISSUE THREAD

**Issue by Black-Fox-2022** [hiddevdploeg/Billboard#24]
Force unwrapping is the issue :(

![Bildschirmfoto 2023-09-21 um 13 06 44](https://github.com/hiddevdploeg/Billboard/assets/106263486/5615ee1a-666b-4f8d-8c1c-289629a43f50)

**Comment by hiddevdploeg** [comment]
Should be fixed now :)
