### ISSUE TITLE
Fetching one or more adverts currently not possible as described in the documentation

### ISSUE THREAD

**Issue by dhaydl** [hiddevdploeg/Billboard#25]
based on the current documentation, it should be possible to fetch an ad via `BillboardViewModel` like this:

``` swift
let newAdvert = try? await viewModel.fetchRandomAd()
advertisement = newAdvert
```

but there are two difference to what is actually implemented in code:

- `fetchRandomAd` needs an URL parameter
- `fetchRandomAd` is static

current workaround:

``` swift
guard  let adsURL = BillboardConfiguration().adsJSONURL else {
    return
}

Task {
    try await BillboardViewModel.fetchRandomAd(from: adsURL)
}
```

a good solution would be to merge `showAdvertisement` and `fetchRandomAd` somehow. what would you say to this?

**Comment by hiddevdploeg** [comment]
```swift
Task {
    try await BillboardViewModel.fetchRandomAd(from: adsURL)
}
```

Should now work :) thanks for letting me know

**Comment by hiddevdploeg** [comment]
I'm sorry I mean it works without the URL now :)
