### ISSUE TITLE
`BillboardCountdownView` not rendering correctly

### ISSUE THREAD

**Issue by dhaydl** [hiddevdploeg/Billboard#27]
`BillboardCountdownView` renders weirdly when counting down the remaining time until the user can dismiss `BillboardBannerView`

**Comment by hiddevdploeg** [comment]
You have an examples screenshots?

**Comment by dhaydl** [comment]
![CleanShot 2023-10-31 at 15 08 15](https://github.com/hiddevdploeg/Billboard/assets/42062676/236b4b24-c518-4d30-a043-350a93b998f4)

this is the Xcode preview of the countdown view. You see that the number 15 is present a long time even though the circle renders correctly and suddenly the numbers are weirdly overlayed

**Comment by dhaydl** [comment]
Hi Hidde,

Was this a helpful explanation or do you need further infos to fix this issue?
